README.md
parkings/admin.py
parkings/api/internal/parking.py
parkings/api/internal/urls.py
parkings/api/operator/parking.py
parkings/api/operator/urls.py
parkings/models/operator.py
parkings/models/parking.py
parkkihubi/settings.py
parkkihubi/urls.py
requirements.in
requirements.txt

Added initial admin UI and initial API implementations (write-only operator and read-only internal).

Initial APIs

---

README.md
parkings/api/operator/parking.py
parkings/factories/__init__.py
parkings/factories/address.py
parkings/factories/faker.py
parkings/factories/operator.py
parkings/factories/parking.py
parkings/factories/user.py
parkings/tests/api/conftest.py
parkings/tests/api/internal/test_parking.py
parkings/tests/api/operator/test_parking.py
parkings/tests/api/utils.py
parkings/tests/conftest.py
parkkihubi/settings.py
requirements-dev.in
requirements-dev.txt
requirements.in
requirements.txt
setup.cfg

- Enabled possibility to update parkings using the operator API
- Implemented factoryboy factories for the models
- Added pytest-factoryboy to autogenerate pytest fixtures of the factories
- Implemented basic tests for internal and operator parking API endpoints
- Upgraded all dev dependency packages

Initial tests

---

README.md

Fix typo in package name in readme

---

parkings/api/common.py
parkings/api/internal/parking.py
parkings/api/operator/parking.py
parkings/tests/api/conftest.py
parkings/tests/api/internal/test_parking.py
parkings/tests/api/operator/test_parking.py
parkings/tests/api/test_common.py
parkings/tests/api/utils.py
parkkihubi/settings.py

Enabled GET for operator API. Operators can only view their own parkings. Created a module for stuff common to both APIs and refactored also common tests to their own module.

Operator API GET

---

parkings/api/public/parking_area.py
parkings/api/public/urls.py
parkkihubi/urls.py

Adds a public API and in it, parking areas, in a somewhat GeoJSON compatible format.

Public API and Parking Areas

---

parkings/api/common.py
parkings/api/public/parking_area.py
parkings/api/public/parking_area_statistics.py
parkings/api/public/urls.py

Adds a real-time public API that shows the amount of parkings per parking area.

Parking area statistics public API

---

post-update
pre-update

Add hooks for deployment/update script to run when updating the code to
new version.

Add update script hooks

---

post-update

Add commands for building and updating dashboard on the server when it
has changed.

post-update: Add commands for deploying dashboard

---

dashboard/src/containers/App.tsx

Add a container around the login form so that it will look better.

Dashboard: Style login view a bit

---

dashboard/src/actions.ts
dashboard/src/api/index.ts
dashboard/src/api/types.ts
dashboard/src/containers/Dashboard.tsx
dashboard/src/containers/LastParkingsTable.ts
dashboard/src/converters.ts
dashboard/src/dispatchers.ts
dashboard/src/reducers.ts
dashboard/src/types.ts
dashboard/tsconfig.json
parkings/api/monitoring/serializers.py
parkings/api/monitoring/urls.py
parkings/api/monitoring/valid_parking.py
parkings/tests/api/monitoring/test_region_statistics.py
parkings/tests/api/monitoring/test_valid_parking.py

Add monitoring API endpoint for listing valid parkings at given time and
use that to list the active parkings at selected time and region in the
Dashboard.
Refs HP-35

Dashboard: Implement active parkings table

---

parkings/importers/__init__.py
parkings/importers/parking_areas.py
parkings/importers/permit_areas.py
parkings/importers/utils.py
parkings/management/commands/import_permit_areas.py
parkings/tests/permit_area_importer_data.xml
parkings/tests/test_permit_area_importer.py

Add a better importer to import PermitAreas
Refs HP-61

Add a better importer to import PermitAreas

---

parkings/admin.py

Add Permit, PermitCacheItem, PermitArea and PaymentZone to admin.

Add new models to admin

---

parkings/importers/__init__.py
parkings/importers/parking_areas.py
parkings/importers/payment_zones.py
parkings/importers/permit_areas.py
parkings/importers/utils.py
parkings/management/commands/import_payment_zones.py
parkings/tests/payment_zone_importer_data.xml
parkings/tests/test_payment_zone_importer.py

* Refactor the importer so that duplication of codes is abstracted
* Add a better importer for paymentZones
Refs HP-61

Refactor the importers 

---

parkings/admin_utils.py
parkings/api/auth/urls.py
parkings/api/enforcement/urls.py
parkings/api/enforcement/valid_parking.py
parkings/api/monitoring/urls.py
parkings/api/monitoring/valid_parking.py
parkings/api/operator/parking.py
parkings/api/operator/urls.py
parkings/api/public/urls.py
parkings/api/url_utils.py
parkings/management/commands/fix_geometries.py
parkings/migrations/0013_parking_terminal_data.py
parkkihubi/settings.py
parkkihubi/urls.py
requirements.in
requirements.txt
setup.cfg

Make code compatible with Django 2.2 and upgrade Django to the latest
version, i.e. 2.2.3.

Upgrade Django to 2.2.3

---

docs/api/enforcement.yaml
docs/api/operator.yaml

Add operator side specification for parking disc parking.

Document Parking Disc API endpoints

---

parkings/api/operator/urls.py

Add basename to parking route in Operator API

Operator: Add basename to route

---

parkings/api/enforcement/check_parking.py
parkings/api/enforcement/operator.py
parkings/api/enforcement/permissions.py
parkings/api/enforcement/permit.py
parkings/api/enforcement/valid_parking.py
parkings/api/operator/parking.py
parkings/factories/__init__.py
parkings/factories/enforcement_domain.py
parkings/tests/api/conftest.py
parkings/tests/api/enforcement/test_activate_permit_series.py
parkings/tests/api/enforcement/test_active_permit_by_external_id.py
parkings/tests/api/enforcement/test_check_parking.py
parkings/tests/api/enforcement/test_operator.py
parkings/tests/api/enforcement/test_permissions.py
parkings/tests/api/enforcement/test_permit.py
parkings/tests/api/enforcement/test_valid_parking.py
parkings/tests/api/operator/test_disc_parking.py
parkings/tests/api/operator/test_parking.py
parkings/tests/conftest.py

This PR adds following stuffs:
* Add domain field to parkings
* Allow enforcers to view only parkings of its enforced domain

Parking visibility by domain

---

requirements-dev.txt
requirements-style.txt
requirements-test.txt
requirements.txt

Update all required Python packages to their newest versions.

Update Python requirements

---

parkings/api/enforcement/permit.py
parkings/tests/api/enforcement/test_activate_permit_series.py
parkings/tests/api/enforcement/test_active_permit_by_external_id.py
parkings/tests/api/enforcement/test_permit.py

This PR adds following stuffs:
* Add current user as the onwer of permitseries
* Limit permit visibility to owner
* Limit permitseries visibility to owner
* Limit activepermit visibility to owner

Permit permitseries visibility

---

parkings/api/common_permit.py
parkings/api/operator/permit.py
parkings/models/permit.py
parkings/tests/api/operator/test_permit_series.py

Didn't dare to ask these changes from @urshala so implemented them
myself. :)
See the commit messages for details.

Various clean-ups to the Operator API Permit implementation

---

parkings/api/common_permit.py
parkings/api/enforcement/enforcement_permit.py
parkings/api/operator/permit.py
parkings/factories/__init__.py
parkings/factories/permit.py
parkings/importers/geojson_payment_zones.py
parkings/importers/geojson_permit_areas.py
parkings/models/permit.py
parkings/models/zone.py
parkings/tests/api/enforcement/test_active_permit_by_external_id.py
parkings/tests/api/enforcement/test_check_parking.py
parkings/tests/api/enforcement/test_permit.py
parkings/tests/api/operator/test_active_permit_by_external_id.py
parkings/tests/api/operator/test_permit.py
parkings/tests/api/operator/test_permit_series.py
parkings/tests/api/utils.py
parkings/tests/conftest.py
parkings/tests/test_admin.py
parkings/tests/test_permit_model.py

There was some bugs and unhandled edge cases in the code related to
Permits, PermitAreas and PermitSeries.  Fix the bugs, improve the
factories and clean-up the code a bit.

Fix and clean-up Permit related code

---

parkings/admin.py

Display domain in related list views and add it as a filter option.

Admin: Add EnforcementDomain to related list views

---

docs/api/enforcement.yaml

Add documentation for new endpoints for fetching valid permits
and valid parkings.

Enforcement: Add documentation for new endpoints

---

parkings/api/enforcement/check_parking.py
parkings/tests/api/enforcement/test_check_parking.py

Ensure check_parking results are filtered to the correct enforcement domain.

check_parking: Add domain filtering

---

parkings/api/operator/parking.py
parkings/models/enforcement_domain.py

Use SlugRelatedField for the Parking.zone in the Operator API and
implement couple other clean-ups.

Simplify Parking.zone handling in the Operator API (HP-105)

---

.sanitizerconfig
.travis.yml
tox.ini

Update new tables and columns to sanitizerconfig and add a section to
Tox and Travis configuration so that sanitizer configuration will be
checked by Travis in the future.
Also add Python 3.8 to test matrix.

Update sanitizer configuration and check it with Travis

---

docs/data_model.svg
docs/data_model.txt

This is a good source of information and now it can also be easily updated, since it's a text file.

docs: Convert data model picture to PlantUML

---

README.md

Update readme with a geojson importer instruction for a
specific domain.
Refs None

Add Geojson importers to readme

---

docs/api/enforcement.yaml
docs/api/operator.yaml
parkings/api/enforcement/valid_permit_item.py
parkings/tests/api/enforcement/test_valid_permit_item.py

* Remove permit_type from the documentation.
* Add permit_type to the valid permit list
* Add example of permit_type

Permit properties

---

.github/workflows/main.yaml
parkings/tests/test_archive_parkings.py
parkings/tests/test_sanitize_parkings.py
parkkihubi/settings.py
tox.ini

* Fix dates in test_archive_parkings and test_sanitize_parkings
* Add couple helpful improvements to settings.py
* Fix CI setup so that tests still pass even though ubuntu18.04 image is no longer available

Fix couple unit tests and CI setup

---

.github/workflows/main.yaml
Dockerfile
docker-compose.yml

Add a test phase that makes sure that the dockerization works properly,
making sure that the containers created with docker-compose can run
pytest and those tests pass.
Also update the Dockerfile to use Python 3.8 instead of Python 3.7.

CI: Add phase to test the dockerization
