City-of-Helsinki/parkkihubi

- requirements-dev.in
- requirements-dev.txt
Werkzeug is needed to use the already included Django-Extensions runserver_plus command. Werkzeug adds a nice debugger when errors happen.
> Add Werkzeug dev requirement for runserver_plus command

- parkings/api/internal/parking.py
- parkings/tests/api/internal/test_parking.py
Both times allow filtering in both directions, ie. the actual filter are
time_start_gte, time_start_lte, time_end_gte and time_end_lte.
> Add start time and end time filters to internal API

- docs/api/operator.yaml
- parkings/api/common.py
- parkings/api/operator/parking.py
- parkings/exception_handler.py
- parkings/tests/api/internal/test_parking.py
- parkings/tests/api/operator/test_parking.py
- parkings/tests/api/utils.py
- parkkihubi/settings.py
Added error code to 403 API errors to make them machine-readable.
The code is returned in `code` field in 403 response body alongside
the default `detail` field.
current codes:
`unknown_error`: Fallback value, should not be used normally
`permission_denied`: for DRF PermissionDenied()
`grace_period_over`: Parking edit grace period has passed
> Api error codes

- parkings/api/operator/parking.py
- parkings/tests/api/internal/test_parking.py
Use UTC timezone for start/end time fields when no timezone is specified
in data of the POST request.
> operator API: Default to UTC for start/end time

- parkings/importers/parking_areas.py
- parkings/tests/parking_area_importer_data.xml
It seems that the avoindata namespace has changed from http to https in
the received XML content.  Amend the importer so that it can import the
data again.
> parking areas importer: Fix namespace of avoindata

- parkings/models/parking.py
- parkings/tests/test_models.py
When a Parking with a terminal_number number is saved, the save function
tries find a terminal by the terminal number.  This lookup does an
implicit conversion to integer, because the Terminal.number field is an
integer field.  That caused couple exceptions.
Fix this by making sure that only an integer or None is passed to the
filter call.
> Parking: Fix converting non-digit to int on save

- parkings/admin.py
- parkings/models/parking.py
Hiding of the registration numbers was only a temporary need.  Make them
visible again.
This reverts commit e9d90b911f6645d44d405e9951c84f400a5f8151.
> Revert "Hide registration numbers in admin"

- parkings/api/enforcement/operator.py
- parkings/api/enforcement/urls.py
- parkings/api/enforcement/valid_parking.py
- parkings/tests/api/enforcement/test_operator.py
- parkings/tests/api/enforcement/test_valid_parking.py
Add API endpoint for listing the operators.
Also add operator identifier to the valid_parking endpoint so that it is
possible to link them properly (not just by name).
> api/enforcement: Add endpoint for operators

- requirements.in
- requirements.txt
Memcached is used in production, so add it to requirements.
This should have been part of commit a0431f1, which added drf-jwt-2fa,
since it uses the Django cache framework.
Refs HP-31
> requirements: Add python-memcached

- post-update
Read the environment variables from etc/env and then, when building the
Dashboard, check if the TIER environment variable is not "prod", use URL
of the test API for the Dashboard.
> post-update: Use test API URL for Dashboard on test tier

- .travis.yml
- post-update
- requirements-dev.txt
- requirements-test.txt
- tox.ini
Allow skipping migrations on deploy and skipping the deployment of
Dashboard with environment variables.
> Changes to post-update hook for pubapi server (HP-50)

- .travis.yml
- requirements-dev.txt
- tox.ini
Use PostgreSQL 10 to test, because that is in use on the servers.
Also make Python 3.5 the default Python version on tests, because that
is in use in the servers.
> Travis: Update PostgreSQL to 10

- .travis.yml
- post-update
- tox.ini
Update Prequ to 1.4.4 in the requirements check configured for Tox and
in the post-update hook script, which is ran by the deployment script.
In addition update Pip to the latest version, 19.0.3, in these same
files.
Remove "pip install pip==18.0" before_script command from the Travis
configuration, since it does not have any effect, because Tox will
create another virtualenv with a different Pip version for the
requirements check anyway.
> Update Prequ to 1.4.4 and Pip to 19.0.3

- parkings/tests/test_region_importer.py
Compare the coordinates with a small delta (1e-7), because the actual
floating point values might differ a bit depending on the platform.
> test_region_importer: Fix float comparison

- parkings/models/permit.py
- parkings/tests/api/enforcement/test_permit.py
PermitCacheItems were not saved when Permits were created via API in bulks.
> Fix PermitCacheItem not being saved

- requirements-dev.txt
- requirements-style.txt
- requirements-test.txt
- requirements.txt
Update all Python requirements to newest available versions except
pytest, which is not yet updated to 5.0.0, because the newest release of
pytest-factoryboy (2.0.2) is not yet compatible with pytest 5.0.0. (See
https://github.com/pytest-dev/pytest-factoryboy/issues/77).
> requirements: Update to newest versions

- parkings/migrations/0019_permits.py
- parkings/models/permit.py
- parkings/tests/api/enforcement/test_permit.py
It seems that full_clean was not called when bulk creating permits.  Fix
this and add test cases which check it.
Also allow empty list as value to "subjects" or "areas" fields, since
that's how it was specified.
> Fix Permit cleaning not being called on bulk creation

- parkings/tests/api/enforcement/test_permit.py
- parkings/validators.py
Interpret the non-timezoned timestamps entered into start_time and
end_time fields of the Permit objects as UTC, since we know that
currently the only client of this API is still pushing non-timezoned
timestamps.  This commit can be reverted when the client side code has
been updated to push timezoned timestamps.
> Permits: Interpret timestamps without timezone as UTC

- parkings/api/enforcement/check_parking.py
- parkings/tests/api/enforcement/test_check_parking.py
Implement better checks for the parameters provided to the check_parking
endpoint.  This should make it harder to crash the endpoint, e.g. by
providing a non-existent location or a location outside of GK25FIN as
input.
Also add more test cases to check other parameters besides the location.
> check_parking: Improve parameter checks

- parkings/models/permit.py
- parkings/tests/api/enforcement/test_permit.py
- parkings/validators.py
Make the permit bulk-creation do timestamp normalization before it
stores the data to database.
Also revert the commit that allowed timestamps without a timezone as
implicit UTC, since it is better to force explicit timezones.
> Permits: Normalize timestamps in bulk-creation

- parkings/admin.py
- parkings/admin_utils.py
- parkings/migrations/0019_permits.py
- parkings/models/permit.py
Make the following improvements to the Django Admin parts in the
parkings app:
* Add PermitSeriesAdmin for browsing permit series
* Tune ordering of the items
* Add new fields to the list displays
* Add date hierarchy to ParkingAdmin and PermitAdmin
* Add area fields to the ParkingAreaAdmin, PaymentZoneAdmin,
PermitAreaAdmin and RegionAdmin to display their area size.
* Improve string presentation of Permit objects.
* Add verbose name for PermitSeries model.
> Improve model admins

- docs/api/operator.yaml
Update the formatting and language of the Operator API documentation.
This PR won't add any new features to the documentation, but just brings it
up to date with the code, improves language, and to use more modern
OpenAPI spec version.
* Update the operator API documentation to OpenAPI specification 3.0.1
format.
* Add missing "terminal_number" field, which has been forgotten from the
documentation, even though the existing implementation has supported it
for quite long already.
* Improve and clean-up some descriptions.
> Update and clean-up Operator API documentation

- .coveragerc
- tox.ini
Tune how the test coverage is measured and reported:
* Make sure that all new apps, e.g. parkkihubi_hel, are included by default.
* Do not ignore the migrations.
* No need to ignore site-packages, rather ignore the .tox directory
Also add --doctest-modules for running the doctests too.                                                                                                                                                       
And, add missing `__init__.py` files, since the tests got broken with this configuration because of them missing.
> Tune coverage reporting configuration

- parkings/models/parking_check.py
The latitude and longitude should be absolute values, since the sign is
told via E/W or N/S letters in the suffix.
> models/parking_check: Fix a bug in _format_coordinates

- .travis.yml
Currently codecov is not working, because there is an issue that it
doesn't work with the coverage 5.0 Python package.  Fix this issue by
making sure that coverage 4.x is used instead.
See the coverage error in the Travis build logs for latest master
builds (e.g. [1]) and the codecov issue [2]
[1] https://travis-ci.org/City-of-Helsinki/parkkihubi/jobs/639843555#L1003
[2] https://github.com/codecov/codecov-python/issues/224
> Travis: Fix codecov to work again

- parkings/factories/__init__.py
- parkings/factories/permit.py
- parkings/factories/user.py
- parkings/migrations/0030_domain_data.py
- parkings/tests/api/enforcement/test_activate_permit_series.py
- parkings/tests/conftest.py
Pasi user in data migration is staff.
Pasi user factory is not needed as staff user can be an owner of
Permitseries.
> Remove pasi user factory

- parkings/importers/geojson_permit_areas.py
- parkings/management/commands/import_geojson_permit_areas.py
- parkings/migrations/0029_enforcement_domain.py
- parkings/migrations/0030_domain_data.py
- parkings/migrations/0031_default_domain.py
- parkings/models/permit.py
- parkings/tests/api/enforcement/test_check_parking.py
- parkings/tests/test_geojson_importing_management_commands.py
- parkkihubi_hel/importers/permit_areas.py
- parkkihubi_hel/management/commands/import_permit_areas.py
- parkkihubi_hel/tests/test_importing_management_commands.py
Add permitted_user a FK to User table in order to identify the Permit
area the user has access to read.
Update 3 migrations to reflect the change:
1. 0029_enforcement_domain add foreign key to User table from
PermitArea with default null
2. 0030_domain_data update PermitArea's permitted_user with PASI user
as default
3. 0031_default_domain update PermitArea for not to accept default
value as null
Update PermitArea and Geojson importer to pass permitted-user as an
argument.
Update test_geojson_importing_management_commands and
test_importing_management_commands to pass PASI user to be used as
permitted_user for PermitArea
> Permitted user for PermitArea

- docs/api/enforcement.yaml
- docs/api/operator.yaml
* Specify the permit area usage restrictions.
* Add "required" to some fields which were supposed to be required.
* Improve description of permit series activation endpoint.
* Move the authentication description to more proper place.
* Update versions of the specs to 1.2.0.beta2
> multicity: Update API documentation

- parkings/api/common_permit.py
- parkings/api/enforcement/enforcement_permit.py
- parkings/api/enforcement/urls.py
- parkings/api/operator/parking.py
- parkings/api/operator/permissions.py
- parkings/api/operator/permit.py
- parkings/api/operator/urls.py
- parkings/tests/api/operator/test_active_permit_by_external_id.py
- parkings/tests/api/operator/test_permit.py
- parkings/tests/api/operator/test_permit_series.py
This PR adds following stuffs:
* Refactor Enforcement API permit endpoints to be reusable in Operator API
* Split the IsOperator permission to make it reusable
* Add permitseries endpoint 
* Add endpoint to activate permitseries
* Add permit endpoint
* Add activepermit endpoint
> Operator permit endpoints

- parkings/api/operator/permit.py
- parkings/api/operator/urls.py
- parkings/tests/api/operator/permit_area.py
- parkings/tests/api/operator/test_permit.py
This PR is based on `operator_permit_endpoints` branch and adds following items:
* Add restriction to operator permit area usage.
* Add permit area endpoint to list the permitted permit areas.
> Permit creation restriction based on permit area

- parkings/api/operator/urls.py
- parkings/api/operator/zone.py
- parkings/models/zone.py
- parkings/tests/api/operator/test_payment_zone.py
Add a new endpoint for listing PaymentZones for permitted operators.
This change has already been documented in fd7bf05.
Also, fix an `UnorderedObjectListWarning` by adding an ordering for the PaymentZone model.
> Operator api: Add endpoint for PaymentZones

- docs/api/enforcement.yaml
- docs/api/operator.yaml
Add a description to Operator and Enforcement API documents mentioning that inactive permits series are pruned automatically after a certain time.
Currently, the pruning is linked to activating new series, but this might be changed at some point and is not considered relevant, so no need to mention it in these endpoint descriptions.
> Document pruning of old PermitSeries

- parkings/migrations/0020_add_paymentzone.py
Ordering was added to PaymentZone Meta options in commit b76902e6c30,
but migrations were not updated, which cause makemigration to generate a
new (unneeded) migration file.  Fix that issue by adding the new option
to the existing 0020_add_paymentzone migration file.
It just a meta data change which doesn't actually change the database
schema (can be checked by generating the new migration and running
"./manage.py sqlmigrate 0036" where 0036 is the number of the generated
migration).  Therefore it's safe to add this ordering field change
directly to the already applied migration.
> Update migration 0020 for PaymentZone ordering

- parkings/api/enforcement/urls.py
- parkings/api/enforcement/valid_parking.py
- parkings/api/enforcement/valid_permit_item.py
- parkings/tests/api/enforcement/test_valid_parking.py
- parkings/tests/api/enforcement/test_valid_permit_item.py
Remove the registration number as a required parameter from valid parking endpoint, enabling all valid parkings to be fetched. However, either time or registration number is required.
Add an endpoint for fetching valid permits for enforcers. Endpoint requires either registration number or time parameter for filtering.
> Enforcement: Enable fetching all valid parkings and permit items

- parkings/api/enforcement/valid_parking.py
- parkings/tests/api/enforcement/test_valid_parking.py
Define a new field type CharOrIntegerField for the zone field to make it
clearer that the returned value could actually be either string or
integer and to avoid loading the PaymentZone object from the database.
Also add a few asserts to the related test case to make sure that the
created two zones are actually in different domains and that the
returned zone code is correct.
> valid_parking: Change zone field definition (HP-104)

- docs/api/enforcement.yaml
- docs/api/operator.yaml
Update the following information to the Operator and Enforcement API
documentations:
* Payment zone can be integer, string, or null
* Permit item list has operator and operator_name fields
* Parking time_end can be null
Also update the documentation version information.
> docs: Update latest changes to documentation (HP-103)

- parkings/api/enforcement/valid_parking.py
- parkings/factories/parking.py
- parkings/tests/api/enforcement/test_valid_parking.py
- parkings/tests/api/operator/test_disc_parking.py
The valid_parking endpoint was failing for disc parkings, since they
don't have a zone and it tried to access "zone.code".  Fix this and
fix the DiscParkingFactory to generate parkings without a zone so that
those cases are also tested.
Another very similar special case are parkings with time_end value, so
while at it, also make sure that those are handled.
> Fix valid_parking for disc parkings and improve tests (HP-106)

- parkings/importers/geojson_importer.py
- parkings/importers/geojson_payment_zones.py
- parkings/importers/geojson_permit_areas.py
- parkings/management/commands/import_geojson_payment_zones.py
- parkings/management/commands/import_geojson_permit_areas.py
Make it possible to specify the Enforcement Domain and the SRID of the
input data when importing from GeoJSON files.
Remove the code that deletes everything else than the imported areas.
> Improve GeoJSON importers (HP-91)

- parkings/importers/geojson_importer.py
- parkings/importers/geojson_payment_zones.py
- parkings/importers/geojson_permit_areas.py
Pass the properties dict as is to the defaults argument in
get_or_create.  This makes the PaymentZone importer work also for zones
that have non-integer domains, since previously it was requred to put
the code to a field named "number", but when that was passed in the
"defaults" argument of get_or_create, it resulted to an error, because
non-integer was tried to be saved to an integer field.
> GeoJSON importers: Improve properties passing

- parkings/api/operator/urls.py
- parkings/api/operator/zone.py
- parkings/tests/api/operator/test_payment_zone.py
The PaymentZone list should not be filtered in the Operator API, but
instead all payment zones should be returned.
> api/operator: Fix PaymentZone list filtering (HP-107)

- parkings/api/common_permit.py
- parkings/tests/api/enforcement/test_active_permit_by_external_id.py
The active_permit_by_external_id endpoints in Enforcement API and
Operator API should operate on the latest active PermitSeries of the
user who is performing the request.  It used to operate on the latest
active PermitSeries regardless of the owner of the series, which made
that endpoint to create the permits to incorrect series some times.
Fix the endpoints by adding correct filtering to the base class
ActivePermitByExternalIdViewSet and add a test case as a regression test
for this bug.
> Fix active_permit_by_external_id series filtering

- parkings/api/enforcement/valid_permit_item.py
Make the base queryset in the ValidPermitItemViewSet limit to the active
permit items rather than doing it in each filter condition separately in
the ValidPermitItemFilter.  This way the active filtering is always done
only once, and there's no risk that it would be skipped if the filter
would allow leaving out both reg_num and time parameters in the future.
> valid_permit_item: Do active filtering in base queryset

- parkings/admin.py
- parkings/models/permit.py
- parkings/tests/test_admin.py
Add more data visible to the permit related views in Django Admin and
add new filtering columns and a date hierarchy to permit lookup items.
Make domain code visible in string representation of PermitArea and
Permit objects.
Also add tests for these admin views and the added functionality.
> Admin: Improve Permit related views

- docs/api/enforcement.yaml
- docs/api/operator.yaml
Fix activepermit endpoint URLs.
Fix "end_date" field name to correct name "end_time".
Remove the parking_info_query endpoint documentation, since it's not
implemented yet.
Update the documentation versions to 1.2.0.rc3.  (Hopefully last rc
before actual release version of the docs.)
> Couple fixes to Enforcement and Operator API documentation

- requirements-cov.txt
- requirements-test.txt
Update codecov to 2.1.0 to fix an issue in uploading coverage data to
codecov.io.  Check [1] for details about why this upgrade is needed.
Also update the coverage package to latest version.
[1] https://community.codecov.io/t/http-400-while-uploading-to-s3-with-python-codecov-from-travis/1428/7
> requirements-cov: Update codecov and coverage

- dashboard/src/config.ts
- dashboard/src/reducers.ts
Add an option to use an env variable for map centre coordinates. Use the original coordinates as default if env variable is not set.
> Dashboard: use env variable for map centre coordinates

- docs/api/enforcement.yaml
- parkings/api/enforcement/valid_permit_item.py
- parkings/pagination.py
- parkings/tests/api/enforcement/test_valid_permit_item.py
- parkings/tests/api/utils.py
The pagination of valid_permit_item endpoint in the Enforcement API
didn't work correctly.  When querying all the pages, the results didn't
always contain all items, but some items "between" the pages were
excluded.  Fix this issue by switching to cursor pagination ordered by
the id field (which is always increasing).
Also improve a few related things:
* Add id and permit_id to the result so that it's easier to verify
that all is there.
* Relax the required parameters, because it is no longer needed to
have the time parameter for pagination.
* Minor improvement to code readability in get_queryset.
> Fix pagination of valid_permit_item endpoint in Enforcement API

- parkings/cron.py
- parkings/forecasts/forecast_parking_counts.py
- parkings/forecasts/utils.py
- parkings/management/commands/forecast_region_parking_counts.py
- parkings/tests/test_forecast_parking_counts.py
- parkkihubi/settings.py
- requirements-dev.txt
- requirements-test.txt
- requirements.in
- requirements.txt
- Add some dependencies
- Functions for training a gradient boosting model to forecast parking counts based on historical data and predicting parking counts 1 week into the future using the trained model.
- Gradient boosting forecast model implemented with CatBoost library.
- Add cron jobs that caches the parking counts and makes the predictions daily. By default the jobs are turned off.
> Add parking forecast model training and predictions

- docker-entrypoint
- run-pytest
Wait for the database to be up before starting pytest.
Also improve the TTY handling, because if the pytest is run with "docker-compose exec -T" in a terminal (TTY) and Ctrl+C is pressed, then the output of the pytest command is just detached from the terminal, but the command still continues to run in the container.  This is not good and therefore we should just pass "-T" when there is no TTY available (e.g. in the CI).
> run-pytest: Wait for database and use TTY if available

- docker-compose.yml
Production was upgraded to PostgreSQL 15.4 so docker postgis needs to be upgraded as well to the closest version.
> Bump docker postgis

- Dockerfile
- docker-compose.yml
Specify platform as "linux/amd64" for the app container in the docker-compose.yml, because that's what it's supposed to be and it won't even work on e.g. ARM based archs. (Some deps won't compile.)
Change the appuser uid to 1000, since that is very often the same uid as the developer's uid on a Linux host, which could avoid some problems when the source tree is mounted as a volume to the container and still being modified from the host.
> Dockerization: Add platform and change user uid

- parkings/migrations/0047_populate_permitarea_allowed_users.py
Fix the function name to run when executing the migration (in forward direction).
> Fix 0047_populate_permitarea_allowed_users migration (HPH-36)

- .github/workflows/main.yaml
The GitHub actions started to fail, because this step was unable to find the deb packages when installing the gdal-bin.  It seems that the problem was related to package lists not being up-to-date and adding "apt-get update" before the installation helps.
> CI: Run apt-get update before install
